### ISSUE TITLE
在全面屏中有bug

### ISSUE THREAD

**Issue by rzdchen** [qiujuer/AirPanel#2]
小米8 SE 手机设置隐藏虚拟键后 
private boolean isOpenSoftKeyboard() {
            return mLastFrame.bottom != 0 && mLastFrame.bottom != mDisplayHeight;
  }
此方法失效， mLastFrame.bottom != mDisplayHeight; 总是为true。

**Comment by rzdchen** [comment]
这个应该算是小米8 SE的bug，不管是否隐藏虚拟键 （activity.getWindowManager().getDefaultDisplay().getMetrics(metrics);
            mDisplayHeight =  metrics.heightPixels;）获取的屏幕高度都是一样的。

**Comment by qiujuer** [comment]
应该是刘海等问题导致的，我最近看一下哈。看看能否做一次修复。

**Comment by rzdchen** [comment]
加了一个或的条件。
![image](https://user-images.githubusercontent.com/13955472/45867265-a2088e00-bdb5-11e8-8649-7bf28416b3a3.png)
![image](https://user-images.githubusercontent.com/13955472/45867304-b482c780-bdb5-11e8-8e9a-2af7a96116b4.png)

**Comment by qiujuer** [comment]
该问题已修复，使用：1.2.0 版本即可。
